add gui for reverse effect
mruby-zest/mruby-zest-build pull request #105
Opened 2023-07-06 20:31 UTC by friedolino78

[https://github.com/zynaddsubfx/zynaddsubfx/pull/255](https://github.com/zynaddsubfx/zynaddsubfx/pull/255)

2024-11-30 20:51 UTC, JohannesLorenz requested changes

2024-11-30 20:51 UTC, JohannesLorenz commented on src/mruby-zest/example/ZynReverse.qml
> +        Knob {
I cannot see the controls for delay, crossfade and Syncmode. Maybe you need to update test.json?

2024-11-30 20:52 UTC, JohannesLorenz commented on Makefile
> +install:
Maybe a  `git rebase master` helps? (Pure guessing)

2024-11-30 21:08 UTC, friedolino78 commented on Makefile
> +	#touch src/mruby-widget-lib/src/api.c
indeed. that was not intended.

2024-11-30 21:18 UTC, JohannesLorenz commented on src/mruby-zest/example/ZynReverse.qml
> +        Knob {
I forgot `git pull` on the UI, now it works. Resolving my comment.

2025-02-15 21:27 UTC, JohannesLorenz approved these changes
As usual, the `test.json` looks diff looks strange, but the PR itself looks good and I tested it.

2025-03-01 18:05 UTC, merged